#!/bin/sh

pactl set-card-profile alsa_card.pci-0000_00_1f.3 output:analog-stereo+input:analog-stereo
pactl set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-lineout
pactl set-source-port alsa_input.pci-0000_00_1f.3.analog-stereo analog-input-rear-mic
pactl set-source-volume alsa_input.pci-0000_00_1f.3.analog-stereo 65%

