* Install dependencies

sudo apt install -y git libtool gcc autotools-dev autoconf pkg-config zlib1g-dev check emacs25 i3 tree htop gitk texinfo texlive-full nfs-common gnuplot-x11 vlc python-minimal dvdbackup mkisofs libtool-bin devscripts astyle openssh-server git-lfs picocom ncurses-dev lzop libncursesw5-dev rpm2cpio filezilla ubuntu-restricted-extras valgrind brasero git-email afl xvnc4viewer python3-pip bison flex libssl-dev global nmap python-pygments bmap-tools
mkdir -p ~/dev
cd ~/dev
git clone https://github.com/mferland/distroconf.git mfedistro

* OpenCL

sudo apt install mesa-opencl-icd
sudo apt install opencl-headers
sudo apt install ocl-icd-opencl-dev

Mesa and LLVM PPA:

sudo add-apt-repository ppa:paulo-miguel-dias/pkppa
sudo apt-get update

* Add to dialout group

sudo gpasswd --add ${USER} dialout

* Configure Terminal

echo "export TERMINAL=\"gnome-terminal --hide-menubar\"" >> .bashrc

* Configure key repeat

echo "xset r rate 280 25" > ~/.xprofile

* Configure i3

mkdir -p ~/.config/i3
cp ~/dev/mfedistro/i3.conf ~/.config/i3/config

* Install fonts

cd ~
mkdir .fonts && cd .fonts
wget https://cdn.proggyfonts.net/wp-content/downloads/ProggyClean.ttf.zip
unzip ProggyClean.ttf.zip
rm Licence.txt Readme.txt ProggyClean.ttf.zip

* Install Emacs Packages

mkdir -p ~/.emacs.d/site-lisp
mkdir -p ~/.saves
cp ~/dev/mfedistro/init.el ~/.emacs.d/init.el

** Dash (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/dash
git clone https://github.com/magnars/dash.el.git ~/.emacs.d/site-lisp/dash
cd ~/.emacs.d/site-lisp/dash
git checkout -b mfe 2.16.0

** with-editor (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/with-editor
git clone https://github.com/magit/with-editor.git ~/.emacs.d/site-lisp/with-editor
cd ~/.emacs.d/site-lisp/with-editor
git checkout -b mfe v2.8.1

** magit-popup (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/magit-popup
git clone https://github.com/magit/magit-popup.git ~/.emacs.d/site-lisp/magit-popup
cd ~/.emacs.d/site-lisp/magit-popup
git checkout -b mfe v2.13.0
make

** graph.el (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/graphql
git clone https://github.com/vermiculus/graphql.el.git ~/.emacs.d/site-lisp/graphql
cd ~/.emacs.d/site-lisp/graphql
git checkout -b mfe 0.1.1

** treepy.el (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/treepy
git clone https://github.com/volrath/treepy.el ~/.emacs.d/site-lisp/treepy
cd ~/.emacs.d/site-lisp/treepy
git checkout -b mfe 0.1.1

** ghub (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/ghub
git clone https://github.com/magit/ghub.git ~/.emacs.d/site-lisp/ghub
cd ~/.emacs.d/site-lisp/ghub
git checkout -b mfe v3.2.0
make

** magit

mkdir -p ~/.emacs.d/site-lisp/magit
git clone https://github.com/magit/magit.git ~/.emacs.d/site-lisp/magit
cd ~/.emacs.d/site-lisp/magit
git checkout -b mfe v2.90.1
echo "LOAD_PATH = -L ${HOME}/.emacs.d/site-lisp/magit/lisp" > config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/dash" >> config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/ghub" >> config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/graphql" >> config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/magit-popup" >> config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/treepy" >> config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/with-editor" >> config.mk
make

More info:
https://github.com/magit/magit/blob/master/Documentation/magit.org

** emacs-async (req. by helm)

mkdir -p ~/.emacs.d/site-lisp/emacs-async
git clone https://github.com/jwiegley/emacs-async.git ~/.emacs.d/site-lisp/emacs-async
cd ~/.emacs.d/site-lisp/emacs-async
git checkout -b mfe v1.9.3
make

** popup-el (req. by helm)

mkdir -p ~/.emacs.d/site-lisp/popup-el
git clone https://github.com/auto-complete/popup-el.git ~/.emacs.d/site-lisp/popup-el
cd ~/.emacs.d/site-lisp/popup-el
git checkout -b mfe v0.5.3

** helm

mkdir -p ~/.emacs.d/site-lisp/helm
git clone https://github.com/emacs-helm/helm.git ~/.emacs.d/site-lisp/helm
cd ~/.emacs.d/site-lisp/helm
git checkout -b mfe v3.2
EMACSLOADPATH="${HOME}/.emacs.d/site-lisp/emacs-async:" make

** expand-region

mkdir -p ~/.emacs.d/site-lisp/expand-region
git clone https://github.com/magnars/expand-region.el.git ~/.emacs.d/site-lisp/expand-region
cd ~/.emacs.d/site-lisp/expand-region
git checkout -b mfe 0.11.0

** bb-mode

mkdir -p ~/.emacs.d/site-lisp/bb-mode
git clone https://github.com/mferland/bb-mode.git ~/.emacs.d/site-lisp/bb-mode

** dts-mode

mkdir -p ~/.emacs.d/site-lisp/dts-mode
git clone https://github.com/bgamari/dts-mode.git ~/.emacs.d/site-lisp/dts-mode

** powerline

mkdir -p ~/.emacs.d/site-lisp/powerline
git clone https://github.com/milkypostman/powerline.git ~/.emacs.d/site-lisp/powerline

** go-mode

mkdir -p ~/.emacs.d/site-lisp/go-mode
git clone https://github.com/dominikh/go-mode.el.git ~/.emacs.d/site-lisp/go-mode

** ggtags

mkdir -p ~/.emacs.d/site-lisp/ggtags
git clone https://github.com/leoliu/ggtags.git ~/.emacs.d/site-lisp/ggtags

** alert (slack)

mkdir -p ~/.emacs.d/site-lisp/alert
git clone https://github.com/jwiegley/alert.git ~/.emacs.d/site-lisp/alert

** circe (slack)

mkdir -p ~/.emacs.d/site-lisp/circe
git clone https://github.com/jorgenschaefer/circe ~/.emacs.d/site-lisp/circe

** emojify (slack)

mkdir -p ~/.emacs.d/site-lisp/emojify
git clone https://github.com/iqbalansari/emacs-emojify.git ~/.emacs.d/site-lisp/emojify

** ht (slack)

mkdir -p ~/.emacs.d/site-lisp/ht
git clone https://github.com/Wilfred/ht.el.git ~/.emacs.d/site-lisp/ht

** oauth2 (slack)

mkdir -p ~/.emacs.d/site-lisp/oauth2
git clone https://github.com/emacsmirror/oauth2.git ~/.emacs.d/site-lisp/oauth2

** request (slack)

mkdir -p ~/.emacs.d/site-lisp/request
git clone https://github.com/tkf/emacs-request.git ~/.emacs.d/site-lisp/request

** websocket (slack)

mkdir -p ~/.emacs.d/site-lisp/websocket
git clone https://github.com/ahyatt/emacs-websocket.git ~/.emacs.d/site-lisp/websocket

** slack

mkdir -p ~/.emacs.d/site-lisp/slack
git clone https://github.com/yuya373/emacs-slack.git ~/.emacs.d/site-lisp/slack

Follow instructions at: https://github.com/yuya373/emacs-slack#how-to-get-token-the-harder-yet-officially-sanctioned-way

*** Token

Open and sign into the slack customization page,
e.g. https://my.slack.com/customize, right click anywhere > inspect
element. Open the console and paste:

window.prompt("your api token is: ", TS.boot_data.api_token)

** yaml

mkdir -p ~/.emacs.d/site-lisp/yaml-mode
git clone https://github.com/yoshiki/yaml-mode.git ~/.emacs.d/site-lisp/yaml-mode

* Install Emacs Server

mkdir -p ~/.config/systemd/user
cp ~/dev/mfedistro/emacs.service ~/.config/systemd/user
systemctl --user enable emacs

mkdir -p ~/bin
cp ~/dev/mfedistro/edit ~/bin/edit
chmod 755 ~/bin/edit
echo "export EDITOR=~/bin/edit" >> ~/.bashrc

cp ~/dev/mfedistro/lock ~/bin/lock
chmod 755 ~/bin/lock

* Weechat

sudo apt-get install dirmngr gpg-agent apt-transport-https
sudo apt-key adv --keyserver hkps://keys.openpgp.org --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E
echo "deb https://weechat.org/ubuntu bionic main" | sudo tee /etc/apt/sources.list.d/weechat.list
echo "deb-src https://weechat.org/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list.d/weechat.list
sudo apt-get update
sudo apt-get install weechat-curses weechat-plugins weechat-python weechat-perl

mkdir -p ~/.weechat/python/autoload
cd ~/.weechat/python
curl -O https://raw.githubusercontent.com/wee-slack/wee-slack/master/wee_slack.py
ln -s ../wee_slack.py autoload

See: https://github.com/wee-slack/wee-slack#3-start-weechat

* Configure NFS mounts

mkdir -p ~/nas/doc
mkdir -p ~/nas/download
mkdir -p ~/nas/music
mkdir -p ~/nas/picture
mkdir -p ~/nas/video

export TMPFILE=$(mktemp)
echo "" >> $TMPFILE
echo "# local network mounts" >> $TMPFILE
for m in doc download music picture video; do echo "freenas.doom.priv:/mnt/mfe/${m} /home/marc/nas/${m} nfs rsize=8192,wsize=8192,timeo=14,intr 0 0" >> $TMPFILE; done;
sudo -E /bin/sh -c "cat $TMPFILE >> /etc/fstab"

* Xmodmap

echo "clear Mod4" > ~/.Xmodmap
echo "add Mod4 = Muhenkan" >> ~/.Xmodmap

* IBus

ibus-setup
# set shortcut to <Ctrl> <Shift> <Super> space
# Show property panel: Hide automatically
# Add French Canadian keyboard and US English
# uncheck "Use system keyboard layout"
# Note: make sure keyboard dip switch are: 001010

* VirtualBox

echo "deb http://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee -a /etc/apt/sources.list
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y virtualbox-5.2
sudo apt-get install -y dkms

** Install symlink to ~/mnt

cd
mkdir VirtualBox\ VMs
ln -sf /home/marc/mnt/VirtualBox\ VMs/ VirtualBox\ VMs

** Install Extension Pack (for USB2-3 support)

NOTE: Check the latest version first.

wget https://download.virtualbox.org/virtualbox/5.2.32/Oracle_VM_VirtualBox_Extension_Pack-5.2.32.vbox-extpack
sudo VBoxManage extpack install --replace Oracle_VM_VirtualBox_Extension_Pack-5.2.32.vbox-extpack
sudo usermod -aG vboxusers marc
rm Oracle_VM_VirtualBox_Extension_Pack-5.2.32.vbox-extpack
reboot

** Disable auto capture

Auto capture prevents me from switching desktop when the focus is on
the VirtualBox window.

- File -> Preferences
- Input
- Uncheck 'Auto Capture Keyboard'

* Vagrant

wget https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.deb
sudo dpkg -i vagrant_2.2.5_x86_64.deb
rm vagrant_2.2.5_x86_64.deb

* Skype

Go to: https://www.skype.com/en/get-skype/
sudo dpkg -i skypeforlinux-64.deb

* NXP Pins Tool

Go to: https://www.nxp.com/pages/pins-tool-for-i.mx-application-processors:PINS-TOOL-IMX?tab=Design_Tools_Tab
sudo dpkg -i pins-tool-for-imx-processors-v5-1_amd64.deb

* Install ssh key pair
* Spotify

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update
sudo apt-get install -y spotify-client

* Docker

sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
# Note: Artful package still not available, this is why I'm using zesty
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
sudo apt-get update
sudo apt-get install -y docker-ce
# test
sudo docker run hello-world

* i3status

mkdir -p ~/.config/i3status/
cp ~/dev/mfedistro/i3status.conf ~/.config/i3status/config

* libdvdcss

sudo apt-get install libdvd-pkg
sudo dpkg-reconfigure libdvd-pkg

* Terminal

Monospace Regular 12

* git

git config --global user.name "Marc Ferland"
git config --global user.email marc.ferland@gmail.com
git config --global sendemail.from "ferlandm@amotus.ca"
git config --global sendemail.smtpuser "marc.ferland@gmail.com"
git config --global sendemail.smtpserver "smtp.googlemail.com"
git config --global sendemail.smtpencryption tls
git config --global sendemail.smtpserverport 587

* dput

touch ~/.dput.cf
echo "[mentors]" >> ~/.dput.cf
echo "fqdn = mentors.debian.net" >> ~/.dput.cf
echo "incoming = /upload" >> ~/.dput.cf
echo "method = http" >> ~/.dput.cf
echo "allow_unsigned_uploads = 0" >> ~/.dput.cf
echo "progress_indicator = 2" >> ~/.dput.cf
echo "# Allow uploads for UNRELEASED packages" >> ~/.dput.cf
echo "allowed_distributions = .*" >> ~/.dput.cf

* gpg

gpg --import ~/nas/??/mykey_pub.gpg
gpg --allow-secret-key-import --import ~/mykey_sec.gpg
gpg --list-keys

* BACKUP

** GPG

gpg --list-keys
gpg --output mykey_pub.gpg --armor --export KEY
gpg --output mykey_sec.gpg --armor --export-secret-key KEY
cp mykey_*.gpg ~/nas/??

** SSH

cp -a ~/.ssh ~/nas/??
>>>>>>> Add more stuff

** Firefox

Export bookmarks.

* WORK

mkdir ~/mnt
sudo mount /dev/sdb1 ./mnt
sudo chmod 755 ./mnt
echo "/dev/sdb1 /home/marc/mnt ext4 rw,exec 0 0" | sudo tee -a /etc/fstab
