* Install dependencies

sudo apt install -y git libtool gcc autotools-dev autoconf pkg-config zlib1g-dev check emacs25 i3 tree htop gitk texinfo texlive-full nfs-common gnuplot-x11 vlc python-minimal dvdbackup mkisofs libtool-bin devscripts astyle openssh-server git-lfs picocom ncurses-dev lzop libncursesw5-dev rpm2cpio filezilla ubuntu-restricted-extras valgrind
mkdir -p ~/dev
cd ~/dev
git clone https://github.com/mferland/distroconf.git mfedistro

* Add to dialout group

sudo gpasswd --add ${USER} dialout

* Configure Terminal

echo "export TERMINAL=\"gnome-terminal --hide-menubar\"" >> .bashrc

* Configure i3

mkdir -p ~/.config/i3
cp ~/dev/mfedistro/i3.conf ~/.config/i3/config

* Install fonts

cd ~
mkdir .fonts && cd .fonts
wget https://cdn.proggyfonts.net/wp-content/downloads/ProggyClean.ttf.zip
unzip ProggyClean.ttf.zip
rm Licence.txt Readme.txt ProggyClean.ttf.zip

* Install Emacs Packages

mkdir -p ~/.emacs.d/site-lisp
mkdir -p ~/.saves
cp ~/dev/mfedistro/init.el ~/.emacs.d/init.el

** Dash (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/dash
git clone https://github.com/magnars/dash.el.git ~/.emacs.d/site-lisp/dash
cd ~/.emacs.d/site-lisp/dash
git checkout -b mfe 2.14.1

** with-editor (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/with-editor
git clone https://github.com/magit/with-editor.git ~/.emacs.d/site-lisp/with-editor
cd ~/.emacs.d/site-lisp/with-editor
git checkout -b mfe v2.7.2

** magit-popup (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/magit-popup
git clone https://github.com/magit/magit-popup.git ~/.emacs.d/site-lisp/magit-popup
cd ~/.emacs.d/site-lisp/magit-popup
git checkout -b mfe v2.12.3
make

** ghub (req. by magit)

mkdir -p ~/.emacs.d/site-lisp/ghub
git clone https://github.com/magit/ghub.git ~/.emacs.d/site-lisp/ghub
cd ~/.emacs.d/site-lisp/ghub
git checkout -b mfe v2.0.0
make

** magit

mkdir -p ~/.emacs.d/site-lisp/magit
git clone https://github.com/magit/magit.git ~/.emacs.d/site-lisp/magit
cd ~/.emacs.d/site-lisp/magit
git checkout -b mfe 2.12.1
echo "LOAD_PATH = -L ${HOME}/.emacs.d/site-lisp/magit/lisp" > config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/dash" >> config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/with-editor" >> config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/magit-popup" >> config.mk
echo "LOAD_PATH += -L ${HOME}/.emacs.d/site-lisp/ghub" >> config.mk
make

More info:
https://github.com/magit/magit/blob/master/Documentation/magit.org

** emacs-async (req. by helm)

mkdir -p ~/.emacs.d/site-lisp/emacs-async
git clone https://github.com/jwiegley/emacs-async.git ~/.emacs.d/site-lisp/emacs-async
cd ~/.emacs.d/site-lisp/emacs-async
git checkout -b mfe v1.9.3
make

** popup-el (req. by helm)

mkdir -p ~/.emacs.d/site-lisp/popup-el
git clone https://github.com/auto-complete/popup-el.git ~/.emacs.d/site-lisp/popup-el
cd ~/.emacs.d/site-lisp/popup-el
git checkout -b mfe v0.5.3

** helm

mkdir -p ~/.emacs.d/site-lisp/helm
git clone https://github.com/emacs-helm/helm.git ~/.emacs.d/site-lisp/helm
cd ~/.emacs.d/site-lisp/helm
git checkout -b mfe v2.9.2
EMACSLOADPATH="${HOME}/.emacs.d/site-lisp/emacs-async:" make

** expand-region

mkdir -p ~/.emacs.d/site-lisp/expand-region
git clone https://github.com/magnars/expand-region.el.git ~/.emacs.d/site-lisp/expand-region
cd ~/.emacs.d/site-lisp/expand-region
git checkout -b mfe 0.11.0

** bb-mode

mkdir -p ~/.emacs.d/site-lisp/bb-mode
git clone https://github.com/mferland/bb-mode.git ~/.emacs.d/site-lisp/bb-mode

** dts-mode

mkdir -p ~/.emacs.d/site-lisp/dts-mode
git clone https://github.com/bgamari/dts-mode.git ~/.emacs.d/site-lisp/dts-mode

** powerline

mkdir -p ~/.emacs.d/site-lisp/powerline
git clone https://github.com/milkypostman/powerline.git ~/.emacs.d/site-lisp/powerline

* Install Emacs Server

mkdir -p ~/.config/systemd/user
cp ~/dev/mfedistro/emacs.service ~/.config/systemd/user
systemctl --user enable emacs

mkdir -p ~/bin
cp ~/dev/mfedistro/edit ~/bin/edit
chmod 755 ~/bin/edit
echo "export EDITOR=~/bin/edit" >> ~/.bashrc

* Configure NFS mounts

mkdir -p ~/nas/doc
mkdir -p ~/nas/download
mkdir -p ~/nas/music
mkdir -p ~/nas/picture
mkdir -p ~/nas/video

export TMPFILE=$(mktemp)
echo "" >> $TMPFILE
echo "# local network mounts" >> $TMPFILE
for m in doc download music picture video; do echo "freenas.doom.priv:/mnt/mfe/${m} /home/marc/nas/${m} nfs rsize=8192,wsize=8192,timeo=14,intr 0 0" >> $TMPFILE; done;
sudo -E /bin/sh -c "cat $TMPFILE >> /etc/fstab"

* Xmodmap

echo "clear Mod4" > ~/.Xmodmap
echo "add Mod4 = Muhenkan" >> ~/.Xmodmap

* IBus

ibus-setup
# set shortcut to <Ctrl> <Shift> <Super> space
# Show property panel: Hide automatically
# Add French Canadian keyboard and US English
# uncheck "Use system keyboard layout"
# Note: make sure keyboard dip switch are: 001010

* VirtualBox

echo "deb http://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee -a /etc/apt/sources.list
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y virtualbox-5.2
sudo apt-get install -y dkms

* Vagrant

wget https://releases.hashicorp.com/vagrant/2.1.0/vagrant_2.1.0_x86_64.deb
sudo dpkg -i vagrant_2.1.0_x86_64.deb
rm vagrant_2.1.0_x86_64.deb

* Install ssh key pair
* Spotify

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update
sudo apt-get install -y spotify-client

* Docker

sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
# Note: Artful package still not available, this is why I'm using zesty
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
sudo apt-get update
sudo apt-get install -y docker-ce
# test
sudo docker run hello-world

* i3status

mkdir -p ~/.config/i3status/
cp ~/dev/mfedistro/i3status.conf ~/.config/i3status/config

* libdvdcss

sudo apt-get install libdvd-pkg
sudo dpkg-reconfigure libdvd-pkg

* Terminal

Monospace Regular 12

* git

git config --global user.name "Marc Ferland"
git config --global user.email marc.ferland@gmail.com

* dput

touch ~/.dput.cf
echo "[mentors]" >> ~/.dput.cf
echo "fqdn = mentors.debian.net" >> ~/.dput.cf
echo "incoming = /upload" >> ~/.dput.cf
echo "method = http" >> ~/.dput.cf
echo "allow_unsigned_uploads = 0" >> ~/.dput.cf
echo "progress_indicator = 2" >> ~/.dput.cf
echo "# Allow uploads for UNRELEASED packages" >> ~/.dput.cf
echo "allowed_distributions = .*" >> ~/.dput.cf

* gpg

gpg --import ~/nas/??/mykey_pub.gpg
gpg --allow-secret-key-import --import ~/mykey_sec.gpg
gpg --list-keys

* BACKUP

** GPG

gpg --list-keys
gpg --output mykey_pub.gpg --armor --export KEY
gpg --output mykey_sec.gpg --armor --export-secret-key KEY
cp mykey_*.gpg ~/nas/??

** SSH

cp -a ~/.ssh ~/nas/??
>>>>>>> Add more stuff
* WORK

mkdir ~/mnt
sudo mount /dev/sdb1 ./mnt
sudo chmod 755 ./mnt
echo "/dev/sdb1 /home/marc/mnt ext4 rw,exec 0 0" | sudo tee -a /etc/fstab

