* Automated setup

The portable, user-owned parts of this setup are now captured by this
repository.  On a new Omarchy installation:

#+begin_src sh
git clone git@github.com:mferland/distroconf.git ~/dev/distroconf
~/dev/distroconf/bootstrap.sh
#+end_src

The bootstrap installs the package manifests, backs up conflicting files,
links the files under =dotfiles/= with GNU Stow, installs the Emacs and
systemd-user configuration, restores the Omarchy theme/font/background, and
reloads the desktop configuration.  Machine-specific and privileged tasks
such as keyboard firmware rules remain documented separately.  See
[[file:mounts.org][Network mounts]] for the NFS and CIFS setup.

* Basic Setup

- Keyboard Layout: English (US)
- Username: marc
- Password: ******
- Full name: Marc Ferland
- Email Address: marc.ferland@gmail.com
- Hostname: mfe-desktop
- Timezone: America/Montreal
- Install...
- Reboot

* Packages to install

sudo pacman -S 7zip \
astyle \
autoconf \
automake \
base-devel \
bison \
cdrkit \
cdrtools \
check \
chrpath \
cpio \
cmake \
diffstat \
dnsmasq \
dmidecode \
dvdbackup \
emacs \
evtest \
evtest \
firefox \
freerdp \
global \
handbrake \
libaacs \
libbluray \
libdvdcss \
libtool \
man-pages \
nano \
nfs-utils \
nmap \
picocom \
pkg-config \
remmina \
rpcsvc-proto \
strace \
tk \
tree \
usbutils \
uv \
valgrind \
w3m \
wev \
wget

* QEMU Install

pacman -S virt-manager qemu-desktop dnsmasq

* Add ${HOME}/.local/bin to PATH

echo 'export PATH=${HOME}/.local/bin:${PATH}' >> ~/.bashrc

* rtags

git clone --recursive https://github.com/Andersbakken/rtags.git
cd rtags
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
make -j 24
sudo make install

** Install systemd service

mkdir -p ~/.config/systemd/user
cp ~/dev/distroconf/rdm.service ~/.config/systemd/user
cp ~/dev/distroconf/rdm.socket ~/.config/systemd/user
systemctl --user enable rdm.socket
systemctl --user start rdm.socket

** Index Kernel sources

Start by compiling the kernel.

./scripts/clang-tools/gen_compile_commands.py
rc -J .

** Index libzc

sudo apt install bear

Go to libzc source directory:
bear -- make
rc -J .

* git

git config --global user.name "Marc Ferland"
git config --global user.email marc.ferland@gmail.com
git config --global sendemail.from "marc.ferland@gmail.com"
git config --global sendemail.smtpuser "marc.ferland@gmail.com"
git config --global sendemail.smtpserver "smtp.googlemail.com"
git config --global sendemail.smtpencryption tls
git config --global sendemail.smtpserverport 587

* Setup Keyboard

sudo cp 70-keyboard.hwdb /etc/udev/hwdb.d/
sudo chmod 644 /etc/udev/hwdb.d/70-keyboard.hwdb
sudo chown root:root /etc/udev/hwdb.d/70-keyboard.hwdb
sudo systemd-hwdb update
sudo udevadm trigger --verbose --sysname-match='event3'
sudo udevadm info /dev/input/by-path/*-usb-*-kbd | grep -i keyboard_key

* Install Emacs Packages

mkdir -p ~/.emacs.d/site-lisp
mkdir -p ~/.saves
cp ~/dev/distroconf/init.el ~/.emacs.d/init.el

Note: remove ~/.emacs.d/elpa if it exists.

** bb-mode

mkdir -p ~/.emacs.d/site-lisp/bb-mode
git clone https://github.com/mferland/bb-mode.git ~/.emacs.d/site-lisp/bb-mode

** bison

mkdir -p ~/.emacs.d/site-lisp/bison
git clone https://github.com/manateelazycat/bison.git ~/.emacs.d/site-lisp/bison

** flex

mkdir -p ~/.emacs.d/site-lisp/flex
git clone https://github.com/manateelazycat/flex.git ~/.emacs.d/site-lisp/flex

* Install Emacs Server

mkdir -p ~/.config/systemd/user
cp ~/dev/distroconf/emacs.service ~/.config/systemd/user
systemctl --user enable emacs

* Install ssh-key

mkdir -p ~/.ssh
cp ~/nas/doc/backup/ssh/id_rsa ~/.ssh
cp ~/nas/doc/backup/ssh/id_rsa.pub ~/.ssh
ssh -T git@github.com

* Configure YubiKey 5 NFC

See [[file:yubikey.org][the YubiKey 5 NFC setup guide]].

* Install ssh-agent

cp ~/dev/distroconf/ssh-agent.service ~/.config/systemd/user
systemctl --user enable ssh-agent
systemctl --user start ssh-agent

echo 'eval $(systemctl --user show-environment | grep SSH_AUTH_SOCK)' >> ~/.bash_profile
echo 'export SSH_AUTH_SOCK' >> ~/.bash_profile

mkdir -p ~/.ssh
cat <<EOF > ~/.ssh/config
AddKeysToAgent yes
EOF

* Always start sshd

sudo systemctl enable sshd

* Hyperland

** Use US and CA keyboard layouts

sed -i "s/kb_layout\ =.*/kb_layout\ =\ us,ca/g" ~/.config/hypr/input.conf

** Set keyboard options

sed -i "s/kb_options\ =.*/kb_options\ =\ grp:shifts_toggle/g" ~/.config/hypr/input.conf

** Set repeat delay

sed -i "s/repeat_delay\ =.*/repeat_delay\ =\ 400/g" ~/.config/hypr/input.conf

** Configure Monitor (.config/hypr/monitors.conf)

env = GDK_SCALE,1.75
monitor=,preferred,auto,1.6

** Set environment (.config/uwsm/default)

export EDITOR=emacs

# Use firefox as the default browser
BROWSER=firefox

* Enable SSH

sudo systemctl enable sshd
sudo systemctl start sshd

* Configure UFW

sudo ufw allow ssh
sudo ufw status

* Change Clock Format

jq '.clock = {
    "format": "{:L%A %d %B %Y W%U %T %Z  }",
    "interval": 1,
    "tooltip-format": "<tt><small>{calendar}</small></tt>",
    "on-click-right": "omarchy-launch-floating-terminal-with-presentation omarchy-tz-select",
    "timezones": ["", "Europe/London"],
    "calendar": {
      "mode": "year",
      "mode-mon-col": 3,
      "weeks-pos": "right",
      "on-scroll": 1,
      "on-click-right": "mode",
      "format": {
        "months": "<span color='#ffead3'><b>{}</b></span>",
        "days": "<span color='#ecc6d9'><b>{}</b></span>",
        "weeks": "<span color='#99ffdd'><b>W{}</b></span>",
        "weekdays": "<span color='#ffcc66'><b>{}</b></span>",
        "today": "<span color='#ff6699'><b><u>{}</u></b></span>"
      }
    },
    "actions": {
      "on-scroll-up": "tz_up",
      "on-scroll-down": "tz_down"
    }
  }' < ~/.config/waybar/config.jsonc > /tmp/config.jsonc

mv /tmp/config.jsonc ~/.config/waybar/config.jsonc

To test waybar:

pkill waybar && waybar &

* Running virt-manager as normal user

** Add myself to libvirt group

sudo usermod -aG libvirt marc

** Change /etc/libvirt/qemu.conf user and group settings

TODO: Really needed if I am in the libvirt group?

sudo sed -i "s/^user\ =\ .*/user\ =\ \"marc\"/g" /etc/libvirt/qemu.conf
sudo sed -i "s/^group\ =\ .*/group\ =\ \"marc\"/g" /etc/libvirt/qemu.conf
reboot

** Enable libvirtd.socket

sudo systemctl enable libvirtd.socket
systemctl status libvirtd.socket
reboot

** Configure QEMU User session

Open virt-manager

File --> Add Connection
Select QEMU/KVM User User Session
Click OK

** Creating a new VM

1- Open virt-manager
2- Select QEMU/KVM User Session
3- Right click -> New
4- Choose "QEMU/KVM User session" connection
5- At step 5: make sure to select "Usermode networking"

TODO: Really needed to autostart the bridge?
Right click on "QEMU/KVM User Session" from virt-manager
Open "Virtual Network" tab

** Listing networks

sudo virsh net-list --all
sudo virsh net-start default
sudo virsh net-list --all
sudo virsh net-autostart default

* kas

Starting kas-container:
    kas-container --docker-args "--device /dev/net/tun:/dev/net/tun --cap-add=NET_ADMIN"  shell kas-qemu-test.yml

Starting qemu:
    runqemu nographic

See: https://www.marcusfolkesson.se/blog/kas-container-and-qemu/
